parameters:
    virtual_identity_facebook.api_requests: ~
    virtual_identity_facebook.social_entity_class: ~
    virtual_identity_facebook.auto_approve: ~
    virtual_identity_facebook.app_id: ~
    virtual_identity_facebook.app_secret: ~
    virtual_identity_facebook.token: ~
    virtual_identity_facebook.secret: ~
    virtual_identity_facebook.host: ~

services:
    virtual_identity_facebook:
        class: VirtualIdentity\FacebookBundle\Services\FacebookService
        arguments: [@logger, @doctrine.orm.entity_manager, @event_dispatcher]
        calls:
            - [setSocialEntityClass, ["%virtual_identity_facebook.social_entity_class%"]]
            - [setAutoApprove, [%virtual_identity_facebook.auto_approve%]]
            - [setHost, ["%virtual_identity_facebook.host%"]]
            - [setAuthentication, ["%virtual_identity_facebook.app_id%", "%virtual_identity_facebook.app_secret%", "%virtual_identity_facebook.token%", "%virtual_identity_facebook.secret%"]]
            - [setApiRequests, ["%virtual_identity_facebook.api_requests%"]]