parameters:
    virtual_identity_instagram.api_requests: ~
    virtual_identity_instagram.social_entity_class: ~
    virtual_identity_instagram.auto_approve: ~
    virtual_identity_instagram.consumer_key: ~
    virtual_identity_instagram.consumer_secret: ~
    virtual_identity_instagram.token: ~
    virtual_identity_instagram.secret: ~
    virtual_identity_instagram.host: ~

services:
    virtual_identity_instagram:
        class: VirtualIdentity\InstagramBundle\Services\InstagramService
        arguments: [@logger, @doctrine.orm.entity_manager, @event_dispatcher]
        calls:
            - [setSocialEntityClass, ["%virtual_identity_instagram.social_entity_class%"]]
            - [setAutoApprove, [%virtual_identity_instagram.auto_approve%]]
            - [setHost, ["%virtual_identity_instagram.host%"]]
            - [setAuthentication, ["%virtual_identity_instagram.consumer_key%", "%virtual_identity_instagram.consumer_secret%", "%virtual_identity_instagram.token%", "%virtual_identity_instagram.secret%"]]
            - [setApiRequests, ["%virtual_identity_instagram.api_requests%"]]